version: '3.9'

services:
  db:
    image: postgres:15.4
    container_name: citymanager-db
    environment:
      POSTGRES_DB: CityManager
      POSTGRES_USER: CityManager
      POSTGRES_PASSWORD: CityManager
      ALLOW_IP_RANGE: "0.0.0.0/0"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    restart: always

volumes:
  db-data:
    name: cityManager-db-data